name: Deployment

on: [push]

jobs:
  build:
    name: Deployment

    runs-on: ubuntu-latest

    env:
      SERVICE_NAME: cartylify-management-api
      REGION: europe-west1
      PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
      DOCKER_IMAGE_NAME: ${{ secrets.GCLOUD_DOCKER_IMAGE_NAME }}

    steps:
      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '281.0.0'
          service_account_email: ${{ secrets.GCLOUD_SERVICE_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          export_default_credentials: true

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud
        run: gcloud config set project $PROJECT_ID

      - name: Auth docker
        run: gcloud auth configure-docker eu.gcr.io

      - name: Build docker image
        run: npm run docker:build -- $DOCKER_IMAGE_NAME

      - name: Publish docker image
        run: docker push $DOCKER_IMAGE_NAME

      - name: Deploy
        run: gcloud run deploy $SERVICE_NAME
          --service-account=${{ secrets.GCLOUD_SERVICE_EMAIL }}
          --region=$REGION
          --image=$DOCKER_IMAGE_NAME
          --platform managed
          --allow-unauthenticated
          --verbosity=debug
          --port=8080
